name: Build and Inspect Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'   # dispara também quando fizer push de tags como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.latest.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build And Publish Image
        uses: docker/build-push-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ github.token }}
          registry: docker.pkg.github.com
          # ✅ alterado o nome do repositório aqui
          repository: ${{ github.repository }}/Versionamento-Imagens_Docker
          tag_with_ref: true
          push: true

      - name: Get Latest Image
        id: latest
        uses: shrink/actions-docker-latest-image@v1
        with:
          repository: docker.pkg.github.com/${{ github.repository }}/Versionamento-Imagens_Docker

  inspect:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to GitHub Package Registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Inspect Image
        run: |
          docker pull ${{ needs.build.outputs.image }}
          docker image inspect ${{ needs.build.outputs.image }}

