name: Build and Inspect Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # dispara quando fizer push de tags como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-and-push.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sanitize ref name for Docker tag
        run: |
          REF_TAG=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]' | tr '/_ ' '--')
          echo "REF_TAG=$REF_TAG" >> $GITHUB_ENV
          echo "Sanitized REF_TAG: $REF_TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:${{ env.REF_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:latest

  inspect:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Debug Docker Tags
        run: |
          echo "Verificando se a imagem existe no registry:"
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:${{ env.REF_TAG }} || echo "Imagem não encontrada"

      - name: Inspect Docker Image
        run: |
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:${{ env.REF_TAG }}
