name: Build and Inspect Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # dispara quando fizer push de tags como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.sanitize-tag.outputs.tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Sanitize ref name for Docker tag
        id: sanitize-tag
        run: |
          REF_TAG=$(echo "${GITHUB_REF_NAME}" \
            | tr '[:upper:]' '[:lower:]' \
            | sed 's/[^a-z0-9.-]/-/g' \
            | sed 's/^-//' \
            | sed 's/-$//')
          echo "tag=$REF_TAG" >> $GITHUB_OUTPUT
          echo "Sanitized REF_TAG: $REF_TAG"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:${{ steps.sanitize-tag.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:latest

  inspect:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Inspect Docker Image
        run: |
          IMAGE_TAG="${{ needs.build.outputs.tag }}"
          echo "Inspecting image with tag: $IMAGE_TAG"
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:$IMAGE_TAG
          
      - name: Pull image from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:${{ needs.build.outputs.tag }}

      - name: Inspect Docker Image
        run: |
          docker image inspect ${{ secrets.DOCKERHUB_USERNAME }}/versionamento-imagens-docker:${{ needs.build.outputs.tag }}
