name: Build and Inspect Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'   # dispara quando fizer push de tags como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.build-and-push.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
         context: .
         push: true
         tags: |
          ghcr.io/${{ github.repository_owner }}/versionamento-imagens-docker:${{ github.ref_name }}
          ghcr.io/${{ github.repository_owner }}/versionamento-imagens-docker:latest

          
  inspect:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Inspect Docker Image
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/versionamento-imagens-docker:${{ github.ref_name }}
          docker image inspect ghcr.io/${{ github.repository_owner }}/versionamento-imagens-docker:${{ github.ref_name }}
