name: Build and Inspect Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'   # dispara quando fizer push de tags como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image: ${{ steps.build-and-push.outputs.image }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase owner
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Sanitize ref name for Docker tag
        run: |
          REF_TAG=$(echo "${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]' | tr '/_' '--')
          echo "REF_TAG=$REF_TAG" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/versionamento-imagens-docker:${{ env.REF_TAG }}
            ghcr.io/${{ env.OWNER_LOWER }}/versionamento-imagens-docker:latest

  inspect:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Inspect Docker Image
        run: |
          docker pull ghcr.io/${{ env.OWNER_LOWER }}/versionamento-imagens-docker:${{ env.REF_TAG }}
          docker image inspect ghcr.io/${{ env.OWNER_LOWER }}/versionamento-imagens-docker:${{ env.REF_TAG }}
